[33mcommit ca963d907a7f2199c627a2d8335f1c5eeb521ec0[m[33m ([m[1;36mHEAD -> [m[1;32mmaster[m[33m)[m
Author: Luis Carlo Hernandez <luish77302@gmail.com>
Date:   Mon Oct 14 18:37:22 2024 -0700

    add index

[1mdiff --git a/index.html b/index.html[m
[1mnew file mode 100644[m
[1mindex 0000000..47c37d2[m
[1m--- /dev/null[m
[1m+++ b/index.html[m
[36m@@ -0,0 +1,14 @@[m
[32m+[m[32m<!DOCTYPE html>[m
[32m+[m[32m<html lang="en">[m
[32m+[m[32m<head>[m
[32m+[m[32m    <meta charset="UTF-8">[m
[32m+[m[32m    <meta name="viewport" content="width=device-width, initial-scale=1.0">[m
[32m+[m[32m    <title>Document</title>[m
[32m+[m[32m</head>[m
[32m+[m[32m<body>[m
[32m+[m[32m    <h1>Titulo</h1>[m
[32m+[m[32m    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quos deleniti magnam quis commodi placeat ad dolorum explicabo provident eius, odit, perspiciatis dolores eos cupiditate distinctio a? Ipsam modi omnis nihil.</p>[m
[32m+[m[32m    <h2>Titulo</h2>[m
[32m+[m[32m    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Perspiciatis aspernatur nihil vitae, dicta fugit eligendi beatae earum quod omnis, commodi unde ducimus voluptatum quam atque eaque officiis iste velit nostrum!</p>[m
[32m+[m[32m</body>[m
[32m+[m[32m</html>[m
\ No newline at end of file[m
